version: '3.9'

services:
  snasphot-service:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./test/testalbatross-history-consensus:/test/testalbatross-history-consensus
      - ./config.json:/config.json
    restart: unless-stopped
